import type { ClientNotes } from './clientSheets';

// Access Granted Education — FTG's working notes, generated by scripts/xlsx2ts.py.
//
// Kept apart from the statements deliberately. These are drafts about the
// client's own bookkeeping, and this module is imported only when a staff
// member is viewing, so none of it reaches the client at all.

export const ACCESS_GRANTED_NOTES: ClientNotes = {
  'TL;DR': [
    [null, "Access Granted Education", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, "Monthly / YTD Financial TL;DR  ·  prepared by Finance Therapy Group (FTG)", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Industry", "Sustain focus (growing)", "Rebuild focus (declining)", "Staffing driver"],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Jan 2026", null, "Behavioral / Mental Health", "keeping the clinician schedule full, driving client rebooking and retention, and optimizing the payer mix", "client rebooking and retention, filling open session slots, and clinician utilization", "clinician schedules to session volume"],
    [null, "Period From:", "Jan 2026", "Period To:", "Jul 2026", null, null, null, null, null, null, null, null, null, null, "Feb 2026", null, "Childcare / Early Education", "enrollment and attendance, filling open classroom slots, and add-on program revenue", "enrollment, waitlist conversion, and classroom utilization / staff-to-child ratios", "staffing to enrollment and required staff-to-child ratios"],
    [null, "Industry:", "Education / Tutoring", null, null, null, null, null, null, null, null, null, null, null, null, "Mar 2026", null, "Healthcare / Medical Clinic", "patient visit volume, payer mix, and procedures per visit", "appointment fill rate, no-shows, and reimbursement/coding capture", "clinical staffing to patient visit volume"],
    [null, "TL;DR — KEY HIGHLIGHTS  (Jan–Jul 2026)", null, null, null, null, null, null, null, null, null, null, null, null, null, "Apr 2026", null, "Wellness / Therapy / Spa", "keeping the calendar full, rebooking and memberships, and higher-value add-ons", "client rebooking, filling open slots, and the treatment/service mix", "practitioner hours to booking volume"],
    [null, "Metric", "This Period", null, "% of Revenue / Note", null, null, null, null, null, null, null, null, null, null, "May 2026", null, "Education / Tutoring", "student enrollment, session attendance, and program mix", "enrollment, attendance, and instructor utilization", "instructor hours to enrolled sessions"],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Jun 2026", null, "Professional Services", "billable utilization, new engagements, and rate realization", "the sales pipeline, billing cadence, and utilization", "team capacity to billable demand"],
    [null, "Revenue", 327919.22, null, "+99.6% vs prior period", null, null, null, null, null, null, null, null, null, null, "Jul 2026", null, "Other", "protecting revenue, controlling costs, and improving margin", "the top revenue drivers and largest cost lines", "staffing to activity volume"],
    [null, "Gross Profit", 327919.22, null, 1, null, null, null, null, null, null, null, null, null, null, "Aug 2026", null, null, null, null, null],
    [null, "Operating Expense", 317658.79, null, 0.96871, null, null, null, null, null, null, null, null, null, null, "Sep 2026", null, null, null, null, null],
    [null, "Net Income (Loss)", 10260.43, null, 0.03129, null, null, null, null, null, null, null, null, null, null, "Oct 2026", null, null, null, null, null],
    [null, "Ending Cash", 7764.82, null, "+359.4% vs prior period", null, null, null, null, null, null, null, null, null, null, "Nov 2026", null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Dec 2026", null, null, null, null, null],
    [null, "KEY RATIOS", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, "Ratio", "This Period", null, "Rationale", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, "Net Margin (%)", 0.03129, null, "Profit kept per $1 of revenue; thin cushion.", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, "Cash to Expense Ratio", 0.171107, null, "Months of operating expense covered by cash on hand; under one month.", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, "Employee Expense Ratio", 0.811, null, "Payroll-related cost as a share of sales; heavy for the sector.", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "HELPER BLOCK — do not edit", null, null, null, null, null],
    [null, "KEY DRIVERS", null, null, null, null, null, null, null, null, null, null, null, null, null, "Start col index", 13, null, null, null, null],
    [null, "Revenue", "Revenue rose 99.6% vs prior period to $327,919.", null, null, null, null, null, null, null, null, null, null, null, null, "End col index", 19, null, null, null, null],
    [null, "Labor", "Payroll was 81.1% of revenue; contract labor $19,923.", null, null, null, null, null, null, null, null, null, null, null, null, "Months in period", 7, null, null, null, null],
    [null, "Cost base", "Total operating expense $317,659 (96.9% of revenue).", null, null, null, null, null, null, null, null, null, null, null, null, "Prior start index", 6, null, null, null, null],
    [null, "Fixed costs", "Software, subscriptions & insurance ≈ $3,843 over the period, largely fixed regardless of volume.", null, null, null, null, null, null, null, null, null, null, null, null, "Prior end index", 12, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Prior period exists", 1, null, null, null, null],
    [null, "SUMMARY", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, "For Jan–Jul 2026, revenue was $327,919 (+99.6% vs prior period) and net income was $10,260 (3.1% margin). The period was profitable as reported. Cash covers 0.2x of monthly OpEx and payroll is 81.1% of sales. Sustain momentum by student enrollment, session attendance, and program mix. Payroll is the dominant cost lever; align instructor hours to enrolled sessions to protect margin. DATA QUALITY WARNING: $148,050 of income and $42,011 of expense in this period sit in Uncategorized accounts. Excluding both, the period result is ($95,779) - treat every margin figure above as provisional until those entries are coded.", null, null, null, null, null, null, null, null, null, null, null, null, null, "Line item", "Current", "Prior", null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Revenue (AG PS r10)", 327919.22, 164251.02, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Gross Profit (r11)", 327919.22, 164251.02, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Total Expenses (r41)", 317658.79, 168367.87, null, null, null],
    [null, "RECOMMENDATIONS & ACTION PLAN", null, null, null, null, null, null, null, null, null, null, null, null, null, "Net Income (r43)", 10260.43, -4116.85, null, null, null],
    [null, "Area", "Finding", "Recommended Action", "Next-Period Target", "Forecast Impact", null, null, null, null, null, null, null, null, null, "Ending Cash (AG BS r10)", 7764.82, 1690.18, null, null, null],
    [null, "Revenue", "Revenue grew to $327,919 (+99.6% vs prior period).", "Sustain: student enrollment, session attendance, and program mix.", "Aug 2026 onward: sustain the monthly run-rate", "Each 5% revenue lift ≈ $16,396 of additional gross profit.", null, null, null, null, null, null, null, null, null, "Payroll + contractor & consultant", 265942.54, 159225.29, null, null, null],
    [null, "Profitability / Net Margin", "Net margin 3.1%; profitable.", "Protect margin; reinvest selectively.", "Aug 2026 onward: net margin > 0%", "Sustaining margin builds cash reserve.", null, null, null, null, null, null, null, null, null, "Contractor payments (r17)", 19923, null, null, null, null],
    [null, "Operating Costs", "OpEx $317,659 (96.9% of revenue); payroll is the largest line.", "Hold OpEx growth below revenue growth.", "Aug 2026 onward: OpEx < revenue", "Payroll is the biggest line; align instructor hours to enrolled sessions.", null, null, null, null, null, null, null, null, null, "Software, subscriptions & insurance (r15+19+20)", 3843.29, null, null, null, null],
    [null, "Liquidity (Cash / Expense)", "Cash covers 0.2x of monthly operating expense.", "Build cash reserve: time large outflows and tighten collections.", "Aug 2026 onward: keep > 1.5x monthly OpEx", "At the current run-rate, cash covers about 0.2 months of OpEx.", null, null, null, null, null, null, null, null, null, "Uncategorized income (AG PS r9)", 148050, null, null, null, null],
    [null, "Employee Cost Ratio", "Payroll-related cost is 81.1% of sales.", "Labor cost is high — align staffing to visit volume.", "Aug 2026 onward: hold payroll near 81.1% of sales", "Each 1 pp reduction ≈ $3,279 saved per period.", null, null, null, null, null, null, null, null, null, "Uncategorized expense (r40)", 42011.07, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Net income excl. unclassified", -95778.5, null, null, null, null],
    [null, "Live-linked to the AG PS and AG BS tabs. Set Period From / Period To above to change the reporting window.", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  ],
};

export default ACCESS_GRANTED_NOTES;
