import type { ClientNotes } from './clientSheets';

// Uniquely Enough Behavioral Health LLC — FTG's working notes, generated by scripts/xlsx2ts.py.
//
// Kept apart from the statements deliberately. These are drafts about the
// client's own bookkeeping, and this module is imported only when a staff
// member is viewing, so none of it reaches the client at all.

export const UE_NOTES: ClientNotes = {
  'TL;DR': [
    [null, "UNIQUELY ENOUGH BEHAVIORAL HEALTH LLC", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, "Monthly / YTD Financial TL;DR  ·  prepared by Finance Therapy Group (FTG)", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Industry", "Sustain focus (growing)", "Rebuild focus (declining)"],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Jan 2026", null, "Behavioral / Mental Health", "keeping the clinician schedule full, driving client rebooking and retention, and optimizing the payer mix", "client rebooking and retention, filling open session slots, and clinician utilization"],
    [null, "Period From:", "Jan 2026", "Period To:", "Jul 2026", null, null, null, null, null, null, null, null, null, null, "Feb 2026", null, "Childcare / Early Education", "enrollment and attendance, filling open classroom slots, and add-on program revenue", "enrollment, waitlist conversion, and classroom utilization / staff-to-child ratios"],
    [null, "Industry:", "Behavioral / Mental Health", null, null, null, null, null, null, null, null, null, null, null, null, "Mar 2026", null, "Healthcare / Medical Clinic", "patient visit volume, payer mix, and procedures per visit", "appointment fill rate, no-shows, and reimbursement/coding capture"],
    [null, "TL;DR — KEY HIGHLIGHTS  (Jan–Jul 2026)", null, null, null, null, null, null, null, null, null, null, null, null, null, "Apr 2026", null, "Wellness / Therapy / Spa", "keeping the calendar full, rebooking and memberships, and higher-value add-ons", "client rebooking, filling open slots, and the treatment/service mix"],
    [null, "Metric", "This Period", null, "% of Revenue / Note", null, null, null, null, null, null, null, null, null, null, "May 2026", null, "Education / Tutoring", "student enrollment, session attendance, and program mix", "enrollment, attendance, and instructor utilization"],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Jun 2026", null, "Professional Services", "billable utilization, new engagements, and rate realization", "the sales pipeline, billing cadence, and utilization"],
    [null, "Revenue", 835292.95, null, "+26.9% vs prior period", null, null, null, null, null, null, null, null, null, null, "Jul 2026", null, "Other", "protecting revenue, controlling costs, and improving margin", "the top revenue drivers and largest cost lines"],
    [null, "Gross Profit", 835292.95, null, 1, null, null, null, null, null, null, null, null, null, null, "Aug 2026", null, null, null, null],
    [null, "Operating Expense", 780961.37, null, 0.934955, null, null, null, null, null, null, null, null, null, null, "Sep 2026", null, null, null, null],
    [null, "Net Income (Loss)", 48878.14, null, 0.058516, null, null, null, null, null, null, null, null, null, null, "Oct 2026", null, null, null, null],
    [null, "Ending Cash", 192654.9, null, "+48.2% vs prior period", null, null, null, null, null, null, null, null, null, null, "Nov 2026", null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Dec 2026", null, null, null, null],
    [null, "KEY RATIOS", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, "Ratio", "This Period", null, "Rationale", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, "Net Margin (%)", 0.058516, null, "Profit kept per $1 of revenue; solid.", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, "Cash to Expense Ratio", 1.726826, null, "Months of operating expense covered by cash on hand; comfortable buffer.", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, "Employee Expense Ratio", 0.778472, null, "Payroll-related cost as a share of sales; heavy for the sector.", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "HELPER BLOCK — do not edit", null, null, null, null],
    [null, "KEY DRIVERS", null, null, null, null, null, null, null, null, null, null, null, null, null, "Start col index", 13, null, null, null],
    [null, "Revenue", "Revenue rose 26.9% vs prior period to $835,293.", null, null, null, null, null, null, null, null, null, null, null, null, "End col index", 19, null, null, null],
    [null, "Labor", "Payroll was 77.8% of revenue; contract labor $38,064.", null, null, null, null, null, null, null, null, null, null, null, null, "Months in period", 7, null, null, null],
    [null, "Cost base", "Total operating expense $780,961 (93.5% of revenue).", null, null, null, null, null, null, null, null, null, null, null, null, "Prior start index", 6, null, null, null],
    [null, "Fixed costs", "Rent & utilities ≈ $7,293 over the period, largely fixed regardless of volume.", null, null, null, null, null, null, null, null, null, null, null, null, "Prior end index", 12, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Prior period exists", 1, null, null, null],
    [null, "SUMMARY", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, "For Jan–Jul 2026, revenue was $835,293 (+26.9% vs prior period) and net income was $48,878 (5.9% margin). The period was profitable. Cash covers 1.7x of monthly OpEx and payroll is 77.8% of sales. Sustain momentum by keeping the clinician schedule full, driving client rebooking and retention, and optimizing the payer mix. Payroll is the dominant cost lever; align staffing to visit volume to protect margin.", null, null, null, null, null, null, null, null, null, null, null, null, null, "Line item", "Current", "Prior", null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Revenue (UE PL r8)", 835292.95, 658143.86, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Gross Profit (r9)", 835292.95, 658143.86, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Total Expenses (r44)", 780961.37, 564823.46, null, null],
    [null, "RECOMMENDATIONS & ACTION PLAN", null, null, null, null, null, null, null, null, null, null, null, null, null, "Net Income (r55)", 48878.14, 93188.06, null, null],
    [null, "Area", "Finding", "Recommended Action", "Next-Period Target", "Forecast Impact", null, null, null, null, null, null, null, null, null, "Ending Cash (UE BS r11)", 192654.9, 130016.24, null, null],
    [null, "Revenue", "Revenue grew to $835,293 (+26.9% vs prior period).", "Sustain: keeping the clinician schedule full, driving client rebooking and retention, and optimizing the payer mix.", "Aug 2026 onward: sustain the monthly run-rate", "Each 5% revenue lift ≈ $41,765 of additional gross profit.", null, null, null, null, null, null, null, null, null, "Payroll + contract + benefits", 650251.77, 411908.5, null, null],
    [null, "Profitability / Net Margin", "Net margin 5.9%; profitable.", "Protect margin; reinvest selectively.", "Aug 2026 onward: net margin > 0%", "Sustaining margin builds cash reserve.", null, null, null, null, null, null, null, null, null, "Contract labor (r20)", 38064.03, null, null, null],
    [null, "Operating Costs", "OpEx $780,961 (93.5% of revenue); payroll is the largest line.", "Hold OpEx growth below revenue growth.", "Aug 2026 onward: OpEx < revenue", "Payroll is the biggest line; align staffing to visit volume.", null, null, null, null, null, null, null, null, null, "Rent + Utilities (r52+r42)", 7293.19, null, null, null],
    [null, "Liquidity (Cash / Expense)", "Cash covers 1.7x of monthly operating expense.", "Liquidity is healthy; deploy surplus selectively.", "Aug 2026 onward: keep > 1.5x monthly OpEx", "At the current run-rate, cash covers about 1.7 months of OpEx.", null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, "Employee Cost Ratio", "Payroll-related cost is 77.8% of sales.", "Labor cost is high — align staffing to visit volume.", "Aug 2026 onward: hold payroll near 77.8% of sales", "Each 1 pp reduction ≈ $8,353 saved per period.", null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, "Live-linked to the UE PL and UE BS tabs. Set Period From / Period To above to change the reporting window.", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  ],
};

export default UE_NOTES;
